### PR TITLE
Encapsulating the retry logic and checking directory existence before…

### PR DESCRIPTION
**Pull request by HEskandari**
Encapsulated the duplicate Retry logic as well as adding a check to make sure the directory exists before trying to delete it.

### CODE REVIEW

**Comment by HEskandari** [comment]
This would fix #45

**Comment by SimonCropp** [comment]
why do we need to retry file deletion? we know the process that will be locking files. we can wait for it to be dead

**Comment by gbiellem** [comment]
I'll pull the retries out. I already have code in there to watch for the underlying process

**Comment by petersgiles** [comment]
@gbiellem @SimonCropp are we ready to delete this branch?

**Comment by gbiellem** [comment]
Delete it

**Pull request closed without merging**
