### PR TITLE
validation summary

### PR DESCRIPTION
**Pull request by petersgiles**
@distantcam @HEskandari I got the beginnings of a validation summary here but I'm struggling with why it doesn't light up with all the errors 

help appreciated

### CODE REVIEW

**Comment by distantcam** [comment]
@petersgiles Pushed a change that got this working. I'm not sure it's worth creating a full usercontrol for this. It's easy enough to just bind the error string to a textblock and style that up.

**Comment by gbiellem** [comment]
@petersgiles  @distantcam - what's the state of this?

**Comment by petersgiles** [comment]
@gbiellem There is summary of what is wrong with your form at the top. There are merge conflicts with main that I will work through if you're happy for me to go ahead with it

**Comment by gbiellem** [comment]
@petesgiles Yep pull it in

**Comment by gbiellem** [comment]
@petesgiles Yep pull it in

**Pull request merged**
